stop-continue with qmp
ispras/qemu-gui pull request #6
Opened 2018-06-06 15:05 UTC by notawa

first version

2018-06-07 05:39 UTC, Dovgalyuk requested changes
Travis ругается, надо исправить причины.

2018-06-07 05:39 UTC, Dovgalyuk commented on src/QemuGUI.cpp
> +    qemu_stop = new QAction(QIcon(":Resources/stop_disable.png"), "Stop VM", this);
А в кнопку нельзя сразу все иконки засунуть, чтобы вручную не переключать?

2018-06-07 05:39 UTC, Dovgalyuk commented on src/QemuGUI.cpp
> +    //mainToolBar->addAction(QIcon(":Resources/stop.png"), "Stop VM", this, SLOT(stop_machine()));
мусор

2018-06-07 05:39 UTC, Dovgalyuk commented on src/QemuGUI.cpp
> +    terminal_text->setFontFamily("Courier new");
Возможно, тут что-нибудь кроссплатформенное надо.

2018-06-07 05:39 UTC, Dovgalyuk commented on src/QemuGUI.cpp
> +    //terminal_cmd->setPalette(terminal_palette);
Еще мусор

2018-06-07 05:39 UTC, Dovgalyuk commented on src/QemuGUI.cpp
> +            qemu_stop->setEnabled(true);
true это случайно не значение по умолчанию?

2018-06-07 05:39 UTC, Dovgalyuk commented on src/QemuGUI.cpp
> +    monitorSocket.write("{ \"execute\": \"stop\" }");
Вот этот весь QMP надо бы убрать в отдельный класс.

2018-06-07 05:39 UTC, Dovgalyuk commented on src/QemuGUI.cpp
> +        else if (vm_state == VMState::Stopped)
Если машина сама остановится, то состояние не переключится. Наверное она присылает уведомление по QMP?

2018-06-07 09:27 UTC, notawa commented on src/QemuGUI.cpp
> +            qemu_stop->setEnabled(true);
нет

2018-06-08 06:49 UTC, Dovgalyuk requested changes

2018-06-08 06:49 UTC, Dovgalyuk commented on src/QMPInteraction.cpp
> +QByteArray QMPInteraction::init()
Лучше занести сокет сюда, а обмениваться с GUI сигналами/вызовами функций типа "останови машину" - "машина остановлена"

2018-06-08 06:49 UTC, Dovgalyuk commented on src/QMPInteraction.cpp
> +    if (msg.contains("event", Qt::CaseInsensitive))
Парсер лучше сразу взять нормальный.

2018-06-08 06:49 UTC, Dovgalyuk commented on src/QMPInteraction.cpp
> +            return 2;
Вот вместо этого беспредела и нужен сигнал.

2018-06-08 06:49 UTC, Dovgalyuk commented on src/QemuGUI.cpp
> +QIcon QemuGUI::set_button_icon_for_state(QString normal_icon, QString disable_icon)
static?

2018-06-09 17:12 UTC, Dovgalyuk requested changes

2018-06-09 17:12 UTC, Dovgalyuk commented on CMakeFiles/3.11.3/CMakeCCompiler.cmake
> +set(CMAKE_C_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe")
Что происходит?

2018-06-13 07:12 UTC, notawa commented on CMakeFiles/3.11.3/CMakeCCompiler.cmake
> +set(CMAKE_C_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe")
я не знаю!!!!

2018-06-25 06:06 UTC, Dovgalyuk requested changes

2018-06-25 06:06 UTC, Dovgalyuk commented on src/GlobalConfig.cpp
> +bool GlobalConfig::is_has_settings()
странное название - не очень соответствует содержанию

2018-06-25 06:06 UTC, Dovgalyuk commented on src/GlobalConfig.cpp
> +                            terminal_parameters.insert("background", xmlReader.readElementText());
А не лучше это отдельными переменными сделать?

2018-06-25 06:06 UTC, Dovgalyuk commented on src/QemuGUI.h
> +    QTcpSocket qmp_socket;
Что-то ненужное.

2018-06-25 06:06 UTC, Dovgalyuk commented on src/QemuLauncher.cpp
> +    QString qmp = " -qmp \"tcp:127.0.0.1:23,server,nowait\"";
23 используется дважды.
Надо вынести в константы. А в идеале и в настройки.

2018-06-25 11:35 UTC, Dovgalyuk requested changes

2018-06-25 11:35 UTC, Dovgalyuk commented on src/QemuGUI.cpp
> +    if (obj == terminal_cmd)
Видимо терминал стоит вынести в отдельный класс.

2018-06-25 11:35 UTC, Dovgalyuk commented on src/QemuGUI.cpp
> +    terminal_settings_dlg = new QDialog(this);
Этот диалог тоже бы куда-нибудь унести.

2018-06-27 07:55 UTC, Dovgalyuk requested changes

2018-06-27 07:55 UTC, Dovgalyuk commented on src/ConnectionSettingsForm.cpp
> +}
Нужен перевод строки.

2018-06-27 07:55 UTC, Dovgalyuk commented on src/QemuLauncher.cpp
> +QemuLauncher::QemuLauncher(const QString &qemu_install_dir_path, VMConfig *vm, int port_qmp, int port_monitor, QObject *parent)
Зачем порты числа, если они везде как строки?

2018-06-27 07:55 UTC, Dovgalyuk commented on src/ConnectionSettingsForm.cpp
> +    qmp_line = new QLineEdit();
Можно же что-то сделать, чтобы только цифры вводились.

2018-06-27 07:55 UTC, Dovgalyuk commented on src/GlobalConfig.h
> +    QString port_monitor;
Есть смысл в конструкторе записывать туда умолчания.

2018-06-27 07:55 UTC, Dovgalyuk commented on src/QemuGUI.h
> +    QLineEdit *monitor_line;
Что-то лишнее.

2018-06-27 07:55 UTC, Dovgalyuk commented on src/QemuGUI.h
> +    ConnectionSettingsForm *connections_settings;
А эти указатели нужно постоянно хранить?

2018-06-27 07:55 UTC, Dovgalyuk commented on src/TerminalSettingsForm.h
> +#endif //TERMINALSETTINSFORM_H
Перевод строки нужен.

2018-06-27 07:55 UTC, Dovgalyuk commented on src/TerminalTab.cpp
> +    if (global_config->is_terminal_parameters_set())
Может умолчания тупо унести в конфиг, тогда и тут не надо будет проверять.

2018-06-27 09:01 UTC, Dovgalyuk requested changes

2018-06-27 09:01 UTC, Dovgalyuk commented on src/QemuLauncher.h
> +    QemuLauncher(const QString &qemu_install_dir_path, VMConfig *vm, const QString &port_qmp, const QString &port_monitor, QObject *parent = 0);
Слишком длинная строка.

2018-06-27 09:01 UTC, Dovgalyuk commented on src/TerminalTab.cpp
> +    global_config->set_terminal_parameters(QColor("#" + style_list.at(index + 2)), test_text->textColor(), test_text->fontFamily(), test_text->fontPointSize());
Длинные строки.

2018-06-27 09:01 UTC, Dovgalyuk commented on src/TerminalTab.h
> +        const QString &font_family = "Courier New", int font_size = 12);
Значения по умолчанию почему-то живут здесь.

2018-06-27 09:01 UTC, Dovgalyuk commented on src/GlobalConfig.cpp
> +const QString monitor_port_default = "24";
Надо хотя бы поля от значений с помощью комментария отделить, а то сложно их искать будет.

2018-06-27 09:24 UTC, Dovgalyuk approved these changes

2018-06-27 09:25 UTC, merged